# 3.3 伝達関数モデル

## 状態空間モデルと伝達関数モデルの関係

In [1]:
from control.matlab import tf, tf2ss, ss2tf

P = tf([0,1],[1,1,1])
print(P)

<TransferFunction>: sys[0]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


     1
-----------
s^2 + s + 1



In [2]:
Pss = tf2ss(P)
print(Pss)

<StateSpace>: sys[0]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (2): ['x[0]', 'x[1]']

A = [[-1. -1.]
     [ 1.  0.]]

B = [[1.]
     [0.]]

C = [[0. 1.]]

D = [[0.]]



In [3]:
Ptf = ss2tf(Pss)
print(Ptf)

<TransferFunction>: sys[2]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


     1
-----------
s^2 + s + 1



In [4]:
from control.matlab import ssdata
from sympy import Matrix, Symbol
from common import disp_mat
import numpy as np

data = ssdata(Pss)
for name, mat in zip(['A', 'B', 'C', 'D'], data):
    disp_mat(name, mat.astype(np.int8))

A, B, C, D = data
A = Matrix(A.astype(np.int8))
B = Matrix(B.astype(np.int8))
C = Matrix(C.astype(np.int8))
D = Matrix(D.astype(np.int8))
I = Matrix(np.eye(A.shape[0]).astype(np.int8))
s = Symbol('s')

result = C * (s * I - A).inv() * B + D
result

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

Matrix([[1/(s**2 + s + 1)]])

In [5]:
from control import ss, canonical_form
import numpy as np

A = np.array([[1, 2, 3], [3, 2, 1], [4, 5, 0]])
B = np.array([[1], [0], [1]])
C = np.array([[0, 2, 1]])
D = np.array([[0]])

Pss = ss(A, B, C, D)
print(Pss)

<StateSpace>: sys[3]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[1. 2. 3.]
     [3. 2. 1.]
     [4. 5. 0.]]

B = [[1.]
     [0.]
     [1.]]

C = [[0. 2. 1.]]

D = [[0.]]



In [6]:
Pr, T = canonical_form(Pss, form='reachable')
print(Pr)

<StateSpace>: sys[3]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ 3. 21. 24.]
     [ 1.  0.  0.]
     [ 0.  1.  0.]]

B = [[1.]
     [0.]
     [0.]]

C = [[ 1.  9. 27.]]

D = [[0.]]



In [7]:
Po, T = canonical_form(Pss, form='observable')
print(Po)

<StateSpace>: sys[3]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ 3.  1.  0.]
     [21.  0.  1.]
     [24.  0.  0.]]

B = [[ 1.]
     [ 9.]
     [27.]]

C = [[1. 0. 0.]]

D = [[0.]]

